### ISSUE TITLE
坐标准确度问题

### ISSUE THREAD

**Issue by sosoneo** [saitjr/STConvertLL2MC#1]
请问 系统定位到的经纬度和百度定位到的经纬度一样么？

**Comment by saitjr** [comment]
系统坐标系和百度所使用的并不相同，我没考虑到这点，修复中

**Comment by sosoneo** [comment]
//火星坐标转百度坐标
- (CLLocationCoordinate2D )ggToBDEncrypt:(CLLocationCoordinate2D)coord
  {
  double x = coord.longitude, y = coord.latitude;
  
  double z = sqrt(x \* x + y \* y) + 0.00002 \* sin(y \* M_PI);
  double theta = atan2(y, x) + 0.000003 \* cos(x \* M_PI);
  
  CLLocationCoordinate2D transformLocation ;
  transformLocation.longitude = z \* cos(theta) + 0.0065;
  transformLocation.latitude = z \* sin(theta) + 0.006;
  
  return transformLocation;
  }

貌似可以试一下这个 我在coding的源码中看到的

**Comment by saitjr** [comment]
好的，谢谢
